name: Docker

on: push
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Construir imagen de Docker
          run: docker build . --file Dockerfile -t cecimerelo/vizyourdata

        - name: Push VizYourData a Docker Hub
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: cecimerelo/vizyourdata
            tags: $(date +%s)