name: Docker

on: push
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Build and push
          uses: mr-smithers-excellent/docker-build-push@v4
            image: cecimerelo/vizyourdata
            tag: latest
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}