name: Docker

on:
  push:
    branches: [main]

env:
  TEST_IMAGE_PATH: ghcr.io/cecimerelo/vizyourdata:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push Container to Github Package Registry
        uses: actions/checkout@v2
        steps:
          - uses: actions/checkout@v2
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GR_TOKEN }}
      - name: Push
        run: docker build -t $TEST_IMAGE_PATH. && docker push $TEST_IMAGE_PATH

