name: Docker

on: push
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Construir imagen de Docker
          run: docker build . --file Dockerfile -t cecimerelo/vizyourdata:$(date +%s)

        - name: Loguear en DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push
          run: docker push cecimerelo/viz_your_data:$(date +%s)
