name: Docker

on: push

env:
  TEST_IMAGE_PATH: ghcr.io/cecimerelo/vizyourdata-test-env:latest

jobs:
  needs-rebuild:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.needs-rebuild.outputs.files }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: needs-rebuild
        with:
          filters: |
            files:
              - 'Dockerfile'
              - 'package.json'
              - 'tests/**'

  push-container-to-github-package-registry:
    needs: needs-rebuild
    runs-on: ubuntu-latest
    if: ${{ needs.needs-rebuild.outputs.changed == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Log in Github Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GR_TOKEN }}
      - name: Push Container
        run: docker build -t $TEST_IMAGE_PATH . && docker push $TEST_IMAGE_PATH

  test:
    runs-on: ubuntu-latest
    needs: [push-container-to-github-package-registry, needs-rebuild]
    if: always()
    steps:
      - name: Log in Github Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GR_TOKEN }}
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker run -t -v `pwd`:/test $TEST_IMAGE_PATH

